### ISSUE TITLE
Getting "response contains different Upload-Offset value"

### ISSUE THREAD

**Issue by elliottdehn** [tus/tus-java-client#8] opened 2016-06-29 19:58 UTC
Hello, I am currently using the example android application and when I select a picture, and it gets to the end of the upload, the following error gets thrown:

D/Loop: Error occurred: response contains different Upload-Offset value (1386863) than expected (1391815) Error class: class io.tus.java.client.ProtocolException

So it seems like it is undershooting the number of bytes it needs to upload? This seems strange, and I haven't touched the code from the example application, so I don't know what's wrong. I should say that it did successfully upload on a few occasions, but this error happens 95% of the time!

PS I will be hunting this down as I can, I just felt like posting this to see if anyone had any ideas.

Edit: after some logging, I found it might be mixing up numbers?
D/Loop: Looped! 1391815/1386863 (uploaded/total)
D/Loop: Error occurred: response contains different Upload-Offset value (1386863) than expected (1391815) Error clasS: class io.tus.java.client.ProtocolException

**Comment by Acconut** [comment] 2016-06-29 21:19
Thank you for reporting, especially since this seems indeed, very weird. However, I would be pleased if you could provide some more information.

Which Android version are you using?
Is your network unreliable?
Has the file changed before you uploaded it the first time?

Would you even be so kind and get a network capture as described here (http://code.tutsplus.com/tutorials/analyzing-android-network-traffic--mobile-10663) in steps 1 and 2?

> So it seems like it is undershooting the number of bytes it needs to upload?

Not exactly, the app uploaded 1391815 bytes but the server told it that the upload resource only has space for 1386863 bytes (this size is specified by the client before starting the upload). Basically, the client sent more data than the server wanted and complained about this inconsistency.

**Comment by elliottdehn** [comment] 2016-06-29 23:02
version: API level 21
network: very reliable
modification: none (was just a picture)

I can get the network capture tomorrow when I'm back in the office! Thanks for clarifying the error for me.

**Comment by elliottdehn** [comment] 2016-06-30 13:04
Hello,

I attempted to do the TCP Dump. However, I discovered I would need to root my development phone and unfortunately that isn't an option due to the fact I can't connect to our network if the phone is rooted (due to security software that needs to be installed). Is there another option?

**Comment by Acconut** [comment] 2016-06-30 14:05
> I can try it on the emulator. I'll get the report when I can, but I have some other tasks ahead of me today.

It would be superb if you were able to reproduce it in an emulator.

**Comment by elliottdehn** [comment] 2016-07-06 12:57
Hi! A little update - I've played with trying to get tcpdump but I'm having problems getting it to work with Genymotion. I'm using this link to get it:

http://www.androidtcpdump.com/android-tcpdump/compile

However, when I get to step 6, I get a "file not found" despite the file existing. I really haven't found any info on getting this to work which is unfortunate. Are there alternatives to tcpdump or is it really the only one?

**Comment by Acconut** [comment] 2016-07-08 21:44
@elliottdehn That's sad to hear. I will try to find another way. Were you able to reproduce this issue in an emulator?

**Comment by Acconut** [comment] 2016-10-26 20:41
Closing this due to missing information. Feel free to continue the discussion if the situation changes.

**Closed by Acconut** 2016-10-26 20:41 UTC
