### ISSUE TITLE
Upload Issue

### ISSUE THREAD

**Issue by shravanthanvi** [tus/tus-java-client#23] opened 2018-10-06 10:34 UTC
Response contains different upload-offset value than expected

this is coming on tus-android-client 
when using javascript there is no issue

**Comment by Acconut** [comment] 2018-10-06 10:39
Closing this as a duplicate of https://github.com/tus/tus-android-client/issues/25. Please continue the discussion there.

**Closed by Acconut** 2018-10-06 10:39 UTC
